Repository TeamCARDNA/Cardna-iOS, pull requests merged in 2022-01, with the labels that each got.

#4 [#3] 중간과제를 위한 Readme 수정
  README.md
Labels: Docs, ningpop👨‍💻💪

#7 [#5] 카드셀 UI 만들기
  Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
  Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.xib
Labels: kimseawater🌊

#10 [#9] UIView Extension 추가
  Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
  Cardna-iOS/Cardna-iOS/Configuration/AppExtensions/UIView+.swift
Labels: Chore, 무명이🥺

#15 [#6] 카드팩 뷰 navigationBar + BottomSheet 구현
  Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
  Cardna-iOS/Cardna-iOS/Info.plist
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Card.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardBottomSheet.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardBottomSheetViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardViewController.swift
Labels: Feat, 무명이🥺

#21 [Feat] 홈화면 UI Pull Request
  Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/Extensions/HomeViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/Home.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift
Labels: kimseawater🌊, Pull Request

#23 [Feat] 카드 상세뷰 UI
  Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
  Cardna-iOS/Cardna-iOS/Configuration/AppExtensions/String+.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetail.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetailViewController.swift
Labels: kimseawater🌊, Pull Request

#24 [#19] 카드팩 타이틀 간 이동시 indicator bar swipe 구현
  Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Card.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Cell/CardPackTitleCollectionViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Extensions/CardViewController+Extension.swift
Labels: 무명이🥺, Pull Request

#28 [#16] 카드나 작성 뷰 UI 완료
  Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
  Cardna-iOS/Cardna-iOS/Configuration/AppExtensions/UILabel+.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/Extensions/AddCardViewController+Extension.swift
Labels: Feat, ningpop👨‍💻💪

#30 [#20] 카드나/카드너 title과 카드내용 swipe 동기화 구현
  Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Card.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Cell/CardContainerCollectionViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Extensions/CardViewController+Extension.swift
Labels: 무명이🥺, Pull Request

#31 [#26] 대표카드 수정 첫번째뷰 레이아웃
  Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCard.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardHeaderCollectionReusableView.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardViewController.swift
Labels: kimseawater🌊, Pull Request

#33 [#17] addCardBottomSheet 뷰 UI 완료
  Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardBottomSheet.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardBottomSheetViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/Cell/AddCardSymbolCollectionViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/Extensions/AddCardViewController+Extension.swift
Labels: Feat, ningpop👨‍💻💪, Pull Request

#35 [#34] 대표카드 수정 두번째 뷰 UI
  Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardModalViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCard.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardModalViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardViewController.swift
Labels: kimseawater🌊, Pull Request

#37 [#36] 타인이 말하는 나 뷰
  Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
  Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/ListTableViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/ListTableViewCell.xib
  Cardna-iOS/Cardna-iOS/Source/Scene/CardNotYetBox/CardNotYetBox.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/CardNotYetBox/CardNotYetBoxViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/CardNotYetBox/Extensions/CardNotYetBoxViewController+Extension.swift
Labels: kimseawater🌊, Pull Request

#38 [#32] MyPage 설정 뷰 UI 구현완
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPageSetting/Cell/MyPageSettingTitleTableViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPageSetting/Extensions/MyPageSettingViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPageSetting/MyPageSetting.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPageSetting/MyPageSettingViewController.swift
Labels: 무명이🥺, Pull Request

#39 [#29] 카드팩 swipe 안에 collection view로 실제 카드팩 띄우기 구현 완료
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Card.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Cell/CardContainerCollectionViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Extensions/CardViewController+Extension.swift
Labels: 무명이🥺, Pull Request

#41 [#40] 이메일로 친구검색 구현 완 (+empty View 포함)
  Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
  Cardna-iOS/Cardna-iOS/Configuration/AppExtensions/UITextField+.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearch.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearchViewController.swift
Labels: 무명이🥺, Pull Request

#43 [#42] 이니셜 뷰 UI 구현 완료
  Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
  Cardna-iOS/Cardna-iOS/Source/Scene/Initial/Initial.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Initial/InitialViewController.swift
Labels: 무명이🥺, Pull Request

#45 [#44] 마이페이지 메인
  Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
  Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/ProfileCollectionViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/ProfileCollectionViewCell.xib
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/Cell/MyPageFriendsTableViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/Cell/MyPageProfileTableViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/Extensions/MyPageViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/MyPage.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/MyPageViewController.swift
Labels: kimseawater🌊, Pull Request

#48 [#18] 카드 작성 완료 뷰 UI 완성
  Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
  Cardna-iOS/Cardna-iOS/Info.plist
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardBottomSheet.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardBottomSheetViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardCompletedViewController.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardCompletedViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/Extensions/AddCardBottomSheetViewController+Extension.swift
Labels: Feat, ningpop👨‍💻💪, Pull Request

#53 [#51] AppIcon 추가
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/100.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/128.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/144.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/152.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/16.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/167.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/172.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/196.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/20.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/216.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/256.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/32.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/48.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/50.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/512.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/55.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/64.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/72.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/76.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/88.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: Feat, ningpop👨‍💻💪, Pull Request

#55 [#46] 인사이트 뷰 UI 구현 완료
  Cardna-iOS/Cardna-iOS/Source/Scene/Insight/Insight.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Insight/InsightViewController.swift
Labels: 무명이🥺, Pull Request

#58 [#52] 회원가입 뷰 UI 구현
  Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
  Cardna-iOS/Cardna-iOS/Source/Scene/Join/JoinNameViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Join/JoinViewController.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Join/JoinViewController.swift
Labels: Feat, ningpop👨‍💻💪, Pull Request

#63 [#62] 카드셀 레이아웃 디테일 수정
  Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.xib
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Cell/CardContainerCollectionViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/Extensions/HomeViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardModalViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardViewController+Extension.swift
Labels: kimseawater🌊, Pull Request

#65 [#61] 홈 대표카드 UI수정
  Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/Home.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCard.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardHeaderCollectionReusableView.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardViewController.swift
Labels: kimseawater🌊, Pull Request

#66 [#56] 로그인뷰 UI 구현완료
  Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
  Cardna-iOS/Cardna-iOS/Source/Scene/Login/Login.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Login/LoginViewController.swift
Labels: 무명이🥺, Pull Request

#71 [#59] 대표카드 서버통신 후 UI반영
  Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
  Cardna-iOS/Cardna-iOS/Configuration/AppExtensions/UIImageView+.swift
  Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Cell/CardContainerCollectionViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/Extensions/HomeViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/Home.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardModalViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardViewController+Extension.swift
Labels: kimseawater🌊, Pull Request

#73 [#60] 마이페이지 서버통신 완료
  Cardna-iOS/Cardna-iOS/Network/APIModels/MyPageModel/MyPageResponse.swift
  Cardna-iOS/Cardna-iOS/Network/APIServices/MyPageAPI/MyPageService.swift
  Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/ProfileCollectionViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/ProfileCollectionViewCell.xib
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/Cell/MyPageFriendsTableViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/Cell/MyPageProfileTableViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/Extensions/MyPageViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/MyPage.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/MyPageViewController.swift
Labels: kimseawater🌊, Pull Request

#74 [#68] 로그인 서버연동 완료
  Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
  Cardna-iOS/Cardna-iOS/Network/APIModels/LoginModel/LoginRequest.swift
  Cardna-iOS/Cardna-iOS/Network/APIModels/LoginModel/LoginResponse.swift
  Cardna-iOS/Cardna-iOS/Network/APIServices/LoginAPI/LoginRouter.swift
  Cardna-iOS/Cardna-iOS/Network/APIServices/LoginAPI/LoginService.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Login/Extension/LoginViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Login/Login.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Login/LoginViewController.swift
Labels: 무명이🥺, Pull Request

#79 [#27] 카드나 작성 뷰 keyword textField 글자수 제한 추가
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/Extensions/AddCardViewController+Extension.swift
Labels: Feat, ningpop👨‍💻💪, Pull Request

#80 [#50] 카드나 작성 완료 뷰 Lottie 추가
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardCompletedViewController.swift
Labels: Feat, ningpop👨‍💻💪, Pull Request

#84 [#83] 수정 서버통신 완료 (로직 구현 X)
  Cardna-iOS/Cardna-iOS/Network/APIServices/MainCardAPI/MainCardRouter.swift
  Cardna-iOS/Cardna-iOS/Network/APIServices/MainCardAPI/MainCardService.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCard.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardViewController.swift
Labels: kimseawater🌊, Pull Request

#86 [#64] insight 서버통신 완료
  Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
  Cardna-iOS/Cardna-iOS/Network/APIModels/InsightModel/InsightResponse.swift
  Cardna-iOS/Cardna-iOS/Network/APIServices/InsightAPI/InsightRouter.swift
  Cardna-iOS/Cardna-iOS/Network/APIServices/InsightAPI/InsightService.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Insight/Extensions/InsightViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Insight/InsightViewController.swift
Labels: 무명이🥺, Pull Request

#88 [#81] 카드나 작성 뷰 서버연결 완료
  Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
  Cardna-iOS/Cardna-iOS/Network/APIModels/AddCardModel/AddCardRequest.swift
  Cardna-iOS/Cardna-iOS/Network/APIServices/AddCardAPI/AddCardService.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardViewController.swift
Labels: Feat, ningpop👨‍💻💪, Pull Request

#92 [#77] 이메일로 친구 검색 서버 연결
  Cardna-iOS/Cardna-iOS/Network/APIModels/EmailSearchModel/EmailSearchResponse.swift
  Cardna-iOS/Cardna-iOS/Network/APIServices/EmailSearchAPI/EmailSearchRouter.swift
  Cardna-iOS/Cardna-iOS/Network/APIServices/EmailSearchAPI/EmailSearchService.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearch.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearchViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/Extensions/EmailSearchViewController+Extension.swift
Labels: 무명이🥺, Pull Request

#95 [#85] 카드선택 카드나,카드너 조회
  Cardna-iOS/Cardna-iOS/Network/APIModels/CardPackModel/CardPackResponse.swift
  Cardna-iOS/Cardna-iOS/Network/APIServices/CardPackAPI/CardPackRouter.swift
  Cardna-iOS/Cardna-iOS/Network/APIServices/CardPackAPI/CardPackService.swift
  Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.xib
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardModalViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCard.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardModalViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardViewController.swift
Labels: kimseawater🌊, Pull Request

#97 [#96] initial view 화면전환 구현 완료
  Cardna-iOS/Cardna-iOS/Source/Scene/Initial/Initial.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Initial/InitialViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Join/JoinViewController.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Login/Login.storyboard
Labels: 무명이🥺, Pull Request

#100 [#99] 대표카드 수정 카드 가져와서 첫화면에 보여줌
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardModalViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCard.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardModalViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardViewController.swift
Labels: kimseawater🌊, Pull Request

#102 [#78] 이메일 친구 검색시 버튼 UI 토글 구현 + 에셋 상수 추가
  Cardna-iOS/Cardna-iOS/Configuration/Constants/Image.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearch.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearchViewController.swift
Labels: 무명이🥺, Pull Request

#104 [#101] 대표카드 서버연결 후 반영
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardViewController.swift
Labels: kimseawater🌊, Pull Request

#105 [#94] 이메일 검색 실패했을시 화면 처리
  Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearch.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearchViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/Extensions/EmailSearchViewController+Extension.swift
Labels: 무명이🥺, Pull Request

#106 [#98] 이메일로 검색해서 친구 추가/삭제 서버 연결 완료
  Cardna-iOS/Cardna-iOS/Network/APIModels/AddFriendModel/AddFriendRequest.swift
  Cardna-iOS/Cardna-iOS/Network/APIModels/AddFriendModel/AddFriendResponse.swift
  Cardna-iOS/Cardna-iOS/Network/APIServices/AddFriendAPI/AddFriendRouter.swift
  Cardna-iOS/Cardna-iOS/Network/APIServices/AddFriendAPI/AddFriendService.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearchViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/Extensions/EmailSearchViewController+Extension.swift
Labels: 무명이🥺, Pull Request

#107 [#103] 이메일 존재하지 않을 시 화면 전환 자세히 구현
  Cardna-iOS/Cardna-iOS/Network/APIServices/EmailSearchAPI/EmailSearchService.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearchViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/Extensions/EmailSearchViewController+Extension.swift
Labels: 무명이🥺, Pull Request

#110 [#87] 인사이트 카드 nil시 뷰와 서버통신 처리 구현
  Cardna-iOS/Cardna-iOS/Source/Scene/Insight/Insight.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Insight/InsightViewController.swift
Labels: 무명이🥺, Pull Request

#112 [#111] 대표카드 선택 숫자 Count
  Cardna-iOS/Cardna-iOS/Network/APIModels/CardPackModel/CardPackResponse.swift
  Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.xib
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardModalViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardViewController.swift
Labels: Feat, kimseawater🌊

#115 [#113] 대표카드 수정 뷰 Modal 디테일 추가
  Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.xib
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardModalViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCard.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardModalViewController.swift
Labels: kimseawater🌊, Pull Request

#117 [#116] 마이페이지 디테일 잡기
  Cardna-iOS/Cardna-iOS/Source/Scene/CardNotYetBox/CardNotYetBox.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/CardNotYetBox/CardNotYetBoxViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearch.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/Extensions/MyPageViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/MyPage.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/MyPageViewController.swift
Labels: kimseawater🌊, Pull Request

#120 [#67] Login뷰 textfield와 컴포넌트 동기화 + 레이아웃 디테일
  Cardna-iOS/Cardna-iOS/Configuration/AppExtensions/UIView+.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Login/Extension/LoginViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Login/Login.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Login/LoginViewController.swift
Labels: 무명이🥺, Pull Request

#124 [#93] backButton 화면전환 완료
  Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearch.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearchViewController.swift
Labels: 무명이🥺, Pull Request

#125 [#119] insight view 카드 없는 상황 서버처리, empty view처리 구현
  Cardna-iOS/Cardna-iOS/Network/APIServices/InsightAPI/InsightService.swift
Labels: 무명이🥺, Pull Request

#126 [#91] 이메일 검색을 통한 친구 추가 시 토스트 메세지 + 토스트 시간 조정
  Cardna-iOS/Cardna-iOS/Configuration/AppExtensions/UIViewController+.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearchViewController.swift
Labels: Pull Request

#127 [#121] 로그인 뷰 backButton 화면전환 완료
  Cardna-iOS/Cardna-iOS/Source/Scene/Login/Login.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Login/LoginViewController.swift
Labels: 무명이🥺, Pull Request

#131 [#129] 서버연결 분기처리로 로그인 실패 시 토스트 창에 메세지 띄우기
  Cardna-iOS/Cardna-iOS/Configuration/AppExtensions/UIViewController+.swift
  Cardna-iOS/Cardna-iOS/Network/APIServices/LoginAPI/LoginService.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Login/Extension/LoginViewController+Extension.swift
Labels: 무명이🥺, Pull Request

#132 [#118] 마이페이지 -> 친구의 대표카드 화면전환 및 서버연결
  Cardna-iOS/Cardna-iOS/Network/APIServices/MainCardAPI/MainCardRouter.swift
  Cardna-iOS/Cardna-iOS/Network/APIServices/MainCardAPI/MainCardService.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/Cell/MyPageFriendsTableViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/Extensions/MyPageViewController+Extension.swift
Labels: kimseawater🌊, Pull Request

#134 [#133] 친구의 대표카드 버튼 hidden true/false처리
  Cardna-iOS/Cardna-iOS/Configuration/Constants/Image.swift
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/btYoucardpack.imageset/Contents.json
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/btYoucardpack.imageset/btYoucardpack.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/btYoucardpack.imageset/btYoucardpack@2x.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/btYoucardpack.imageset/btYoucardpack@3x.png
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/Home.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/Extensions/MyPageViewController+Extension.swift
Labels: kimseawater🌊, Pull Request

#136 [#135] 이름, 밑줄, 카드 count 추가
  Cardna-iOS/Cardna-iOS/Configuration/AppExtensions/UIColor+.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/Extensions/HomeViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/Home.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/Cell/MyPageFriendsTableViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/Extensions/MyPageViewController+Extension.swift
Labels: kimseawater🌊, Pull Request

#139 [#137] 카드상세뷰 카드나/카드너 분기처리 완료
  Cardna-iOS/Cardna-iOS/Configuration/AppExtensions/UIColor+.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetail.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetailViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/Extensions/HomeViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift
Labels: kimseawater🌊, Pull Request

#141 [#122] 이메일로 검색 결과 화면 구현방식 수정
  Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearch.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearchViewController.swift
Labels: 무명이🥺, Pull Request

#142 [#138] 카드 보관함 서버연결
  Cardna-iOS/Cardna-iOS/Network/APIModels/CardPackModel/CardPackResponse.swift
  Cardna-iOS/Cardna-iOS/Network/APIServices/CardPackAPI/CardPackRouter.swift
  Cardna-iOS/Cardna-iOS/Network/APIServices/CardPackAPI/CardPackService.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/CardNotYetBox/CardNotYetBoxViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/CardNotYetBox/Extensions/CardNotYetBoxViewController+Extension.swift
Labels: kimseawater🌊, Pull Request

#143 [#140] 카드너만들기 서버연결
  Cardna-iOS/Cardna-iOS/Network/APIModels/CardPackModel/CardPackResponse.swift
  Cardna-iOS/Cardna-iOS/Network/APIServices/CardPackAPI/CardPackRouter.swift
  Cardna-iOS/Cardna-iOS/Network/APIServices/CardPackAPI/CardPackService.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetail.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetailViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/CardNotYetBox/CardNotYetBox.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/CardNotYetBox/CardNotYetBoxViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/CardNotYetBox/Extensions/CardNotYetBoxViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/MyPageViewController.swift
Labels: kimseawater🌊, Pull Request

#145 [#90] 카드나/카드너 작성 뷰 분기 처리 완료
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardBottomSheet.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardBottomSheetViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardCompletedViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/Extensions/AddCardViewController+Extension.swift
Labels: Feat, ningpop👨‍💻💪, Pull Request

#149 [#144] 카드너->보관 완료
  Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetail.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetailViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/CardNotYetBox/CardNotYetBox.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift
Labels: kimseawater🌊, Pull Request

#152 [#128] Insight view 카드 조회 결과 구현방식 수정
  Cardna-iOS/Cardna-iOS/Source/Scene/Insight/InsightViewController.swift
Labels: 무명이🥺, Pull Request

#153 [#151] 카드상세 분기처리 및 menu띄우기
  Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetail.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetailViewController.swift
Labels: kimseawater🌊, Pull Request

#155 [#150] Insight 카드 하나만 있을 때 서버 처리 완료
  Cardna-iOS/Cardna-iOS/Network/APIModels/InsightModel/InsightResponse.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Insight/InsightViewController.swift
Labels: Feat, 무명이🥺

#156 [#154] 마이페이지 친구검색
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/Cell/MyPageFriendsTableViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/Extensions/MyPageViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/MyPageViewController.swift
Labels: kimseawater🌊, Pull Request

#158 [#69] 카드팩 재사용 하기위한 뷰 추가
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Card.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardViewController.swift
Labels: 무명이🥺, Pull Request

#160 [#159] 카드팩 재사용 변수 초기화, 친구 이름 데이터 전달용 함수 세팅
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardViewController.swift
Labels: Feat, 무명이🥺

#162 [#161] 카드삭제 구현
  Cardna-iOS/Cardna-iOS/Configuration/AppExtensions/UIViewController+.swift
  Cardna-iOS/Cardna-iOS/Network/APIModels/CardPackModel/CardPackResponse.swift
  Cardna-iOS/Cardna-iOS/Network/APIServices/CardPackAPI/CardPackRouter.swift
  Cardna-iOS/Cardna-iOS/Network/APIServices/CardPackAPI/CardPackService.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetailViewController.swift
Labels: kimseawater🌊, Pull Request

#165 [#163] 설정 뷰 레이아웃 대강 구현 -> 앱잼 이후 수정
  Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPageSetting/Extensions/MyPageSettingViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPageSetting/MyPageSettingRules.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPageSetting/MyPageSettingRulesViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPageSetting/MyPageSettingViewController.swift
Labels: 무명이🥺, Pull Request

#166 [#164] 타인의 카드 상세 디테일
  Cardna-iOS/Cardna-iOS/Network/APIModels/CardDetailModel/CardDetailResponse.swift
  Cardna-iOS/Cardna-iOS/Network/APIServices/CardDetailAPI/CardDetailService.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetail.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetailViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/Extensions/HomeViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift
Labels: kimseawater🌊, Pull Request

#169 [#123] Initial view (진입) 기기대응 layout 수정
  Cardna-iOS/Cardna-iOS/Source/Scene/Initial/Initial.storyboard
Labels: 무명이🥺, Pull Request

#171 [#170] 대표카드 수정에 뱃지 추가
  Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.xib
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/MyPage.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardViewController+Extension.swift
Labels: kimseawater🌊, Pull Request

#173 [#172] 하단 탭바 그라데이션 추가
  Cardna-iOS/Cardna-iOS/Source/Scene/MainTabBarController.swift
Labels: kimseawater🌊, Pull Request

#178 [#176] insight view 진입 시 마다 scroll 위치 맨 처음으로 조정 완료
  Cardna-iOS/Cardna-iOS/Source/Scene/Insight/InsightViewController.swift
Labels: 무명이🥺, Pull Request

#180 [#177] 카드상세뷰 레이아웃(se, mini, pro)
  Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetail.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetailViewController.swift
Labels: kimseawater🌊, Pull Request

#182 [#70] 카드팩 뷰 셀 레이아웃 조정 완료
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Card.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Cell/CardContainerCollectionViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Extensions/CardViewController+Extension.swift
Labels: 무명이🥺, Pull Request

#188 [#108] 회원가입 정규식 등록 및 가입하기 버튼 활성화/비활성화 처리
  Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
  Cardna-iOS/Cardna-iOS/Configuration/AppExtensions/UIColor+.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardBottomSheet.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardBottomSheetViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardYouCompletedViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/Home.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Join/JoinViewController.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Join/JoinViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Join/PrivacyViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Join/ServiceProtocolViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Login/Login.storyboard
Labels: Feat, ningpop👨‍💻💪, Pull Request

#190 [#189] IQKeyboardManagerSwift 설정
  Cardna-iOS/Cardna-iOS/Configuration/Supports/AppDelegate.swift
Labels: kimseawater🌊, Pull Request

#192 [#191] 마이페이지, 보관함 테이블뷰 구분선 수정
  Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/ListTableViewCell.xib
  Cardna-iOS/Cardna-iOS/Source/Scene/CardNotYetBox/CardNotYetBox.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/MyPage.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/MyPageViewController.swift
Labels: kimseawater🌊, Pull Request

#195 [#194] 이메일 추가 후 친구목록 reload
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/MyPageViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardHeaderCollectionReusableView.swift
Labels: kimseawater🌊, Pull Request

#196 [#193] 대표카드 수정 라벨 그라데이션
  Cardna-iOS/Cardna-iOS/Configuration/Constants/Image.swift
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/invalidName.imageset/Contents.json
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/invalidName.imageset/invalidName.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/invalidName.imageset/invalidName@2x.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/invalidName.imageset/invalidName@3x.png
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardHeaderCollectionReusableView.swift
Labels: kimseawater🌊, Pull Request

#198 [#183] 카드팩 서버 연결 완료
  Cardna-iOS/Cardna-iOS/Network/APIServices/CardPackAPI/CardPackRouter.swift
  Cardna-iOS/Cardna-iOS/Network/Base/URLConstant.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Cell/CardContainerCollectionViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Extensions/CardViewController+Extension.swift
Labels: 무명이🥺, Pull Request

#199 [#184] 친구 카드팩 보기 화면전환 연결 완료
  Cardna-iOS/Cardna-iOS/Network/APIServices/CardPackAPI/CardPackRouter.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/Home.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift
Labels: 무명이🥺, Pull Request

#200 [#197] 보라색 좋아요 로티 추가
  Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetail.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetailViewController.swift
Labels: kimseawater🌊

#201 [#148] 카드너 타인 소개 작성 뷰의 서버 연결 작업 (예외처리 X)
  Cardna-iOS/Cardna-iOS/Network/APIModels/AddCardModel/AddCardRequest.swift
  Cardna-iOS/Cardna-iOS/Network/APIServices/AddCardAPI/AddCardService.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardBottomSheetViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardViewController.swift
Labels: Feat, ningpop👨‍💻💪, Pull Request

#203 [#202] 타인의 대표카드 뷰 ui
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/Home.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift
Labels: kimseawater🌊, Pull Request

#204 [#185] 카드팩에서 카드 누르면 상세조회 뷰로 이동 기능 구현
  Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Card.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Cell/CardContainerCollectionViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Extensions/CardViewController+Extension.swift
Labels: 무명이🥺, Pull Request

#206 [#205] 로그인 플로우
  Cardna-iOS/Cardna-iOS/Configuration/AppExtensions/UIViewController+.swift
  Cardna-iOS/Cardna-iOS/Info.plist
  Cardna-iOS/Cardna-iOS/Network/Base/NetworkConstant.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Login/Extension/LoginViewController+Extension.swift
Labels: kimseawater🌊, Pull Request

#208 [#109] 회원가입 뷰 서버 연결 작업
  Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
  Cardna-iOS/Cardna-iOS/Network/APIModels/JoinModel/JoinRequest.swift
  Cardna-iOS/Cardna-iOS/Network/APIModels/JoinModel/JoinResponse.swift
  Cardna-iOS/Cardna-iOS/Network/APIServices/JoinAPI/JoinRouter.swift
  Cardna-iOS/Cardna-iOS/Network/APIServices/JoinAPI/JoinService.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Join/Extension/JoinNameViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Join/JoinNameViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Join/JoinViewController.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Join/JoinViewController.swift
Labels: Feat, ningpop👨‍💻💪, Pull Request

#213 [#212] scroll view indicator bar 없애기
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Card.storyboard
Labels: 무명이🥺, Pull Request

#214 [#212] 카드셀 textColor 수정
  Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.xib
Labels: 무명이🥺, Pull Request

#215 [#212] Insight empty view 수정사항 반영
  Cardna-iOS/Cardna-iOS/Source/Scene/Insight/Insight.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Insight/InsightViewController.swift
Labels: 무명이🥺, Pull Request

#219 [#216] 친구 카드팩 버튼 IBAction 연결 완료
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardYouViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardViewController.swift
Labels: 무명이🥺, Pull Request

#220 [#212] 로그아웃 하고 다시 이니셜뷰로 돌아가기
  Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
  Cardna-iOS/Cardna-iOS/Source/Scene/Initial/Initial.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Initial/InitialNavigationViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPageSetting/Extensions/MyPageSettingViewController+Extension.swift
Labels: 무명이🥺, Pull Request

#222 [#130] 타인이 말하는 나 화면전환 수정
  Cardna-iOS/Cardna-iOS/Source/Scene/CardNotYetBox/CardNotYetBox.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/CardNotYetBox/CardNotYetBoxViewController.swift
Labels: 무명이🥺, Pull Request

#225 [#217] 카드나/카드너 작성 뷰 AutoLayout 설정
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardViewController.swift
Labels: Feat, ningpop👨‍💻💪, Pull Request

#227 [#224] Lottie 파일 추가
  Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Lottie/cardna_splash.json
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Lottie/lottie_cardme.json
Labels: 무명이🥺, Pull Request

#231 [#226] 마이페이지 친구 없을때 튕기는 문제 해결
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/Extensions/MyPageViewController+Extension.swift
Labels: kimseawater🌊, Pull Request

#237 [#235] textField border 제거
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardYouViewController.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardYouViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Join/JoinViewController.storyboard
Labels: Fix, ningpop👨‍💻💪, Pull Request

#238 [#57] swipe해서 뒤로가기 추가, 회원가입뷰의 이름입력에서 뒤로 뷰 하나만 pop 수정
  Cardna-iOS/Cardna-iOS/Source/Scene/Initial/InitialViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Join/JoinNameViewController.swift
Labels: Fix, ningpop👨‍💻💪, Pull Request

#240 [#236] 친구 대표카드 뒤로가기 추가
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/Home.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift
Labels: kimseawater🌊, Pull Request

#241 [#232] asset 5차 추가
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/cardnalogoForsplash.imageset/Contents.json
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/cardnalogoForsplash.imageset/cardnalogoForsplash.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/cardnalogoForsplash.imageset/cardnalogoForsplash@2x.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/cardnalogoForsplash.imageset/cardnalogoForsplash@3x.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/cardplusDoneText.imageset/Contents.json
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/cardplusDoneText.imageset/cardplusDoneText.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/cardplusDoneText.imageset/cardplusDoneText@2x.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/cardplusDoneText.imageset/cardplusDoneText@3x.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/cardyoumakeDoneText.imageset/Contents.json
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/cardyoumakeDoneText.imageset/cardyoumakeDoneText.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/cardyoumakeDoneText.imageset/cardyoumakeDoneText@2x.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/cardyoumakeDoneText.imageset/cardyoumakeDoneText@3x.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/cardyouplusDoneText.imageset/Contents.json
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/cardyouplusDoneText.imageset/cardyouplusDoneText.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/cardyouplusDoneText.imageset/cardyouplusDoneText@2x.png
  Cardna-iOS/Cardna-iOS/Configuration/Resources/Assets.xcassets/cardyouplusDoneText.imageset/cardyouplusDoneText@3x.png
Labels: 무명이🥺, Pull Request

#242 [#230] 비밀번호 찾기 버튼 준비중이라고 하기
  Cardna-iOS/Cardna-iOS/Source/Scene/Login/Login.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Login/LoginViewController.swift
Labels: 무명이🥺, Pull Request

#244 [#243] 삭제 후 카드팩 리로드
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Card.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Extensions/CardViewController+Extension.swift
Labels: Feat, kimseawater🌊

#245 [#187] 설정뷰 버튼 처리
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPageSetting/Extensions/MyPageSettingViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPageSetting/MyPageSetting.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPageSetting/MyPageSettingRules.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPageSetting/MyPageSettingRulesViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPageSetting/MyPageSettingViewController.swift
Labels: Feat, 무명이🥺

#247 [#246] 카드 상세페이지 from 수정
  Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetail.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetailViewController.swift
Labels: kimseawater🌊, Pull Request

#249 [#248] 좋아요 로티 분기처리 및 보라색 추가
  Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetailViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Login/Login.storyboard
Labels: kimseawater🌊, Pull Request

#251 [#250] 대표카드 로직 수정(두번째 수정도 인덱스 체크 잘 되도록 수정)
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardModalViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardModalViewController.swift
Labels: kimseawater🌊, Pull Request

#253 [#252] 대표카드 첫번째 뷰 카운트
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardViewController.swift
Labels: kimseawater🌊, Pull Request

#255 [#254] 대표카드 0개로 만든 후 라벨 사라지게 , 대표카드 추가하면 다시 나타나게
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift
Labels: kimseawater🌊, Pull Request

#257 [#256] 친구 카드팩 reload 오류 해결
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardViewController.swift
Labels: kimseawater🌊, Pull Request

#259 [#258] 사진없을 때 카드너 추가 터지는 오류 수정, 카드팩 기본 숫자 변경
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Card.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCard.storyboard
Labels: kimseawater🌊, Pull Request

#261 [#260] backButton 안눌리는 hotfix 수정
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPageSetting/MyPageSetting.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPageSetting/MyPageSettingViewController.swift
Labels: 무명이🥺, Pull Request

#262 [#207] 레이아웃 마진값 대거 수정 완료
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Card.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/CardNotYetBox/CardNotYetBox.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/Insight/Insight.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPageSetting/MyPageSettingRules.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCard.storyboard
Labels: Fix, 무명이🥺

#265 [#263] 카드나 작성 이미지 있어야만 작성완료 버튼 누르기
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardViewController.swift
Labels: Feat, Fix, ningpop👨‍💻💪, Pull Request

#266 [#181] 홈 empty 라벨
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift
Labels: kimseawater🌊, Pull Request

#269 [#268] font color 적용
  Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetail.storyboard
  Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetailViewController.swift
Labels: 무명이🥺, Pull Request

#272 [#239] navigationController로 변경, 카드나 작성 이미지 선택 오류 Fix
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardBottomSheetViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/Extensions/AddCardBottomSheetViewController+Extension.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardBottomSheetViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardViewController.swift
Labels: Feat, Fix, ningpop👨‍💻💪, Pull Request

#273 [#239] 카드나 작성 완료 후 카드팩으로 이동
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardCompletedViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardViewController.swift
Labels: Feat, Fix, ningpop👨‍💻💪, Pull Request

#279 [#277] 사진 이미지 꽉차게 수정
  Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearch.storyboard
Labels: 무명이🥺, Pull Request

#280 [#278] 초기 데이터 비움
  Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/ProfileCollectionViewCell.xib
  Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetailViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/MyPage.storyboard
Labels: kimseawater🌊, Pull Request

#281 [#239] 카드너 작성 완료 후 카드팩으로 이동 처리
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardYouViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift
Labels: Feat, Fix, ningpop👨‍💻💪, Pull Request

#283 [#282] 홈 404 예외처리
  Cardna-iOS/Cardna-iOS/Network/APIServices/MainCardAPI/MainCardService.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift
Labels: kimseawater🌊, Pull Request

#284 [#270] 모달에서 카드화 되지 않은 메시지창으로 이동 처리
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardBottomSheetViewController.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardViewController.swift
Labels: Feat, Fix, ningpop👨‍💻💪, 무명이🥺, Pull Request

#285 [#276] Cell 파일 토대
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Cell/CardContainerCollectionViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Cell/CardEmptyCollectionViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Cell/CardEmptyCollectionViewCell.xib
Labels: 무명이🥺, Pull Request

#286 [#274] Dark mode 막기
  Cardna-iOS/Cardna-iOS/Info.plist
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Cell/CardContainerCollectionViewCell.swift
Labels: 무명이🥺, Pull Request

#288 [#287] 가로모드 막기
  Cardna-iOS/Cardna-iOS/Configuration/Supports/AppDelegate.swift
Labels: 무명이🥺, Pull Request

#294 [#289] 카드팩 empty view layout 구현
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Cell/CardEmptyCollectionViewCell.swift
  Cardna-iOS/Cardna-iOS/Source/Scene/Card/Cell/CardEmptyCollectionViewCell.xib
Labels: 무명이🥺, Pull Request
